### ISSUE TITLE
Editing *.docx files by WPS Office.

### ISSUE THREAD

**Issue by qelphybox** [chrahunt/docx#29]
Hello @chrahunt, some of my colleagues edit docx files by [WPS Office](https://www.wps.com/). Output docx files succesfully processed by your gem, but not saved. There is an exeption: 

```
/var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/file.rb:262:in `block in read': undefined method `read' for Zip::NullInputStream:Module (NoMethodError)
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry.rb:483:in `get_input_stream'
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/file.rb:230:in `get_input_stream'
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/file.rb:262:in `read'
    from /vagrant/lib/docx/document.rb:111:in `block (2 levels) in save'
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:42:in `block in each'
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:41:in `each'
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:41:in `each'
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/central_directory.rb:182:in `each'
    from /vagrant/lib/docx/document.rb:104:in `block in save'
    from /var/lib/gems/2.3.0/gems/rubyzip-1.1.7/lib/zip/output_stream.rb:53:in `open'
    from /vagrant/lib/docx/document.rb:103:in `save'

```

Obviously, rubyzip gem processes that docx files different from docx files by MS Office.

**Comment by pry0cc** [comment]
Hi! Is this still an issue, or has this been merged somewhere?

I'm hitting this exact same issue right now.
