### ISSUE TITLE
Does docx gem supports .doc also?

### ISSUE THREAD

**Issue by theasteve** [chrahunt/docx#68]
Is there support for `.doc` also?
```doc = Docx::Document.open("example.doc")```

```
[7] pry(LambdaFunctions::LambdaHandler)> File.open("test.doc", 'wb') do |f|
[7] pry(LambdaFunctions::LambdaHandler)*   f.write raw
[7] pry(LambdaFunctions::LambdaHandler)* end  
=> 69632
[8] pry(LambdaFunctions::LambdaHandler)> doc = Docx::Document.open("test.doc")
Errno::ENOENT: No such file or directory - word/document.xml
from /Users/staguilar/.rvm/gems/ruby-2.5.3/gems/rubyzip-1.2.3/lib/zip/file.rb:361:in `get_entry'
```

**Comment by slavajacobson** [comment]
not working for me either...

`TypeError: can't dup NilClass
/home/vagrant/.rvm/gems/ruby-2.3.8/gems/rubyzip-1.1.7/lib/zip/entry_set.rb:52:in `dup'`
